image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  # - gem install bundler -v 1.14.6
  # - gem install bundler:2.1.4
  - bundle install
  # - bundle install --full-index
  # - bundle update sass
  # - bundle update listen
  - gem install jekyll
  - apt-get update && apt-get install -y nodejs

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
